[package]
name = "item_scroll_area"
version = "0.1.0"
authors = ["Jakub Bandola <xxxKubikx@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.61"
publish = false


[dependencies]
eframe = { path = "../../eframe" }
