[package]
name = "z_order"
version = "0.1.0"
authors = ["Max Stoumen <max@mxs.dev>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false


[dependencies]
eframe = { path = "../../crates/eframe", features = [
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
log = "0.4.17"
tracing-subscriber = "0.3"
