[package]
name = "kitdiff"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
eframe = { workspace = true, features = ["glow", "default"] }
egui_extras = { workspace = true, features = ["image", "file", "http"]}
dify = "0.7"
serde.workspace = true
serde_json = "1.0"
image.workspace = true
ignore = "0.4"
clap = { version = "4.0", features = ["derive"] }
git2 = "0.18"
tempfile = "3.0"

[lints]
workspace = true
