[package]
name = "kitdiff"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
eframe = { workspace = true, features = ["glow", "default", "persistence", "ron"] }
egui_extras = { workspace = true, features = ["image", "file", "http"] }
ehttp = { version = "0.5" }
dify = "0.7"
serde.workspace = true
serde_json = "1.0"
image.workspace = true
tempfile = { version = "3.0" }
zip = { version = "5", default-features = false, features = ["deflate"] }
flate2 = { version = "1.1" }
tar = { version = "0.4" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { version = "0.4" }
wasm-bindgen = { version = "0.2" }
js-sys = { version = "0.3" }
web-sys = { version = "0.3", features = ["Window", "Location", "History", "Navigator", "Clipboard", "Performance"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ignore = { version = "0.4" }
clap = { version = "4.0", features = ["derive"] }
git2 = { version = "0.18" }


[lints]
workspace = true
