[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
egui.workspace = true
eframe.workspace = true
