[package]
name = "user_attention"
version = "0.1.0"
authors = ["TicClick <ya@ticclick.ch>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
publish = false

[dependencies]
eframe = { path = "../../crates/eframe" }
