[package]
name = "custom_plot_manipulation"
version = "0.1.0"
authors = ["Ygor Souza <ygor.souza@protonmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.72"
publish = false


[dependencies]
eframe = { path = "../../crates/eframe", features = [
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
egui_plot = { path = "../../crates/egui_plot" }
env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
