[package]
name = "server"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tungstenite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_derive.workspace = true
egui.workspace = true
eframe.workspace = true
