[package]
name = "server"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
tungstenite = "0.18.0"
serde = "1"
serde_json = "*"
serde_derive = "*"
egui = { path = "../../crates/egui" }
eframe = { path = "../../crates/eframe" }
