[package]
name = "server-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.16.0"
egui = { path = "../../crates/egui" }
eframe = { path = "../../crates/eframe" }
serde = "1.0.171"
serde_json = "*"
serde-diff = "0.4.1"
