[package]
name = "egui_plot"
version = "0.22.0"
authors = [
  "Dominik Rössler <dominik@freshx.de>",
  "Emil Ernerfeldt <emil.ernerfeldt@gmail.com>",
  "René Rössler <rene@freshx.de>",
]
description = "Immediate mode plotting for the egui GUI library"
edition = "2021"
rust-version = "1.67"
homepage = "https://github.com/emilk/egui"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/emilk/egui"
categories = ["visualization", "gui"]
keywords = ["egui", "plot", "plotting"]
include = ["../LICENSE-APACHE", "../LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[package.metadata.docs.rs]
all-features = true

[lib]


[features]
default = []


## Allow serialization using [`serde`](https://docs.rs/serde).
serde = ["dep:serde", "egui/serde"]


[dependencies]
egui = { version = "0.22.0", path = "../egui", default-features = false }


#! ### Optional dependencies
## Enable this when generating docs.
document-features = { version = "0.2", optional = true }

serde = { version = "1", optional = true, features = ["derive"] }
