[workspace.package]
name = "client-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tungstenite = "0.18.0"
serde = "1"
serde_json = "*"
serde_derive = "*"
egui = { path = "../../crates/egui" }
eframe = { path = "../../crates/eframe" }

[workspace]
members = ["client", "server"]
