[package]
name = "remote_rendering"
version = "0.1.0"
authors = ["Emma Middleton <middletonel@sky.com>"]
edition = "2021"
publish = false

[dependencies]
tungstenite = "0.18.0"
serde = "1"
serde_json = "*"
serde_derive = "*"
egui = { path = "../../crates/egui" }
eframe = { path = "../../crates/eframe" }
egui_demo_lib = { path = "../../crates/egui_demo_lib" }
serde-diff = { git = "https://github.com/linguini11/serde-diff.git" }
