# https://github.com/marketplace/actions/require-labels
# Check for existence of labels
# See all our labels at https://github.com/rerun-io/rerun/issues/labels

name: Pull Request Labels

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for a "do-not-merge" label
        uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "do-not-merge"

      - name: Require at least one label
        uses: mheap/github-action-required-labels@v3
        with:
          mode: minimum
          count: 1
          labels: "CI, dependencies, docs and examples, ecolor, eframe, egui_extras, egui_glow, egui_plot, egui-wgpu, egui-winit, egui, epaint, exclude from changelog, typo"
