name: preview_comment.yml
on:
  pull_request_target:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        env:
          URL_SLUG: ${{ github.event.number }}-${{ github.head_ref }}
        with:
          message: |
            Preview is being built...
            
            Preview will be available at https://egui-pr-preview.github.io/pr/${{ env.URL_SLUG }}
            
            View snapshot changes at [kitdiff](https://rerun-io.github.io/kitdiff/?url=${{ github.event.pull_request.html_url }})
          comment_tag: 'egui-preview'

