name: Check spelling and links
on: [pull_request]

jobs:
  typos:
    # https://github.com/crate-ci/typos
    # Add exceptions to .typos.toml
    # install and run locally: cargo install typos-cli && typos
    name: typos
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v5

      - name: Check spelling of entire workspace
        uses: crate-ci/typos@v1.38.0

  lychee:
    name: lychee
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Link Checker
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2.6.1
        with:
          # I guess reddit doesn't like github action IPs
          # We need to exclude CHANGELOG.md since we don't want to have a CI failure everytime some contributor decides
          # to change their username.
          args: >-
            --exclude localhost
            --exclude reddit.com
            --exclude-path "CHANGELOG\.md$"
            "**/*.md"
            "**/*.toml"
